### ISSUE TITLE
Unknow attributes should be `attribute.attribute` 

### ISSUE THREAD

**Issue by sporto** [lpil/html-lustre-converter#8]
```
<nav class="flex" aria-label="Breadcrumb">
  Hello
</nav>
```

Translates to 
```
html.nav(
  [attribute("aria-label", "Breadcrumb"), attribute.class("flex")],
  [text("Hello
")],
)
``

Note `attribute("aria-label", "Breadcrumb")`
This should be `attribute.attribute` just like `attribute.class`

**Comment by lpil** [comment]
This is also correct

**Comment by sporto** [comment]
How come is this correct?
What are the assumed imports?

Why would `class` be `attribute.class`. But an unknown attribute just `attribute`?

Thanka

**Comment by lpil** [comment]
Because that's correct for the documented imports.

**Comment by sporto** [comment]
What documented imports?
Don't you think this is inconsistent?
Maybe the imports should appear in the converter output.

**Comment by lpil** [comment]
In the documentation on hexdocs. It's not inconsistent, no.

Could be useful to have them in the app somewhere, aye!

**Comment by sporto** [comment]
Oh, I found it, thanks

```
import lustre/element/html
import lustre/attribute.{attribute}
import lustre/element.{element, text}
```

Maybe consider this instead
```
import lustre/element/html
import lustre/attribute
import lustre/element
```

Which is more robust. i.e doesn't assume that `attribute`, `element` and `text` functions are in scope.
